# generated by action0-client-openapi v0.1.0 from petstore.json — do not edit
"""Typed API client for Petstore 1.0.0."""

from .client import PetstoreClient
from .models import Animal
from .models import Cat
from .models import Companion
from .models import CreateTokenResponse
from .models import Dog
from .models import Owner
from .models import Pet
from .models import PetStatus
from .operations import CreatePet
from .operations import CreateToken
from .operations import DeletePet
from .operations import GetPet
from .operations import GetPetPhoto
from .operations import ListPets
from .operations import ReplacePet

__all__ = [
    "Animal",
    "Cat",
    "Companion",
    "CreatePet",
    "CreateToken",
    "CreateTokenResponse",
    "DeletePet",
    "Dog",
    "GetPet",
    "GetPetPhoto",
    "ListPets",
    "Owner",
    "Pet",
    "PetStatus",
    "PetstoreClient",
    "ReplacePet",
]
