# generated by action0-client-openapi v0.1.1 from petstore.json — do not edit
"""Typed API client for Petstore 1.0.0."""

from .client import PetstoreClient
from .errors import BadRequestError
from .errors import DefaultError
from .errors import NotFoundError
from .models import Animal
from .models import Cat
from .models import Companion
from .models import CreateTokenResponse
from .models import Dog
from .models import Error
from .models import HealthRecord
from .models import Owner
from .models import Pet
from .models import PetStatus
from .operations import CreatePet
from .operations import CreateToken
from .operations import DeletePet
from .operations import GetInventory
from .operations import GetPet
from .operations import GetPetPhoto
from .operations import ListPets
from .operations import ReplacePet
from .operations import UploadPetPhoto

__all__ = [
    "Animal",
    "BadRequestError",
    "Cat",
    "Companion",
    "CreatePet",
    "CreateToken",
    "CreateTokenResponse",
    "DefaultError",
    "DeletePet",
    "Dog",
    "Error",
    "GetInventory",
    "GetPet",
    "GetPetPhoto",
    "HealthRecord",
    "ListPets",
    "NotFoundError",
    "Owner",
    "Pet",
    "PetStatus",
    "PetstoreClient",
    "ReplacePet",
    "UploadPetPhoto",
]
