# generated by action0-client-openapi v0.1.1 from petstore.json — do not edit

from __future__ import annotations

from action0.client import APIClient
from action0.client import BackendT_co
from action0.req import Request


class PetstoreClient(APIClient[BackendT_co]):
    """The Petstore API client."""

    def __init__(
        self,
        backend: BackendT_co,
        token: str,
        api_key_auth: str,
        base_url: str = "https://petstore.example.com/v1",
    ) -> None:
        """
        :param backend: any sync, async or Twisted backend
        :param token: the bearer token
        :param api_key_auth: the API key sent as the api_key query parameter
        :param base_url: the API root
        """
        super().__init__(backend, base_url, headers={"Authorization": f"Bearer {token}"})
        self._api_key_auth = api_key_auth

    def prepare(self, request: Request) -> Request:
        """
        Add the query credentials to every request.

        :param request: the request built from an operation
        :return: the request to actually send
        """
        request = super().prepare(request)
        request.url.query.add("api_key", self._api_key_auth)
        return request
