# generated by action0-client-openapi v0.1.0 from petstore.json — do not edit

from __future__ import annotations

import datetime
import enum
from dataclasses import dataclass
from typing import Any
from typing import TypeAlias


class PetStatus(enum.Enum):
    """The pet's sale status."""

    AVAILABLE = "available"
    ON_SALE = "on-sale"
    SOLD = "sold"


@dataclass
class Owner:
    """The ``Owner`` model."""

    name: str
    class_: str | None = None


def owner_from_json(data: Any) -> Owner:
    """
    Build a :py:class:`Owner` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the Owner
    """
    return Owner(
        name=data["name"],
        class_=data.get("class"),
    )


@dataclass
class Cat:
    """The ``Cat`` model."""

    species: str
    name: str
    meow: bool


def cat_from_json(data: Any) -> Cat:
    """
    Build a :py:class:`Cat` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the Cat
    """
    return Cat(
        species=data["species"],
        name=data["name"],
        meow=data["meow"],
    )


@dataclass
class Dog:
    """The ``Dog`` model."""

    species: str
    name: str
    bark: bool


def dog_from_json(data: Any) -> Dog:
    """
    Build a :py:class:`Dog` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the Dog
    """
    return Dog(
        species=data["species"],
        name=data["name"],
        bark=data["bark"],
    )


#: A pet's companion animal.
Companion: TypeAlias = "Cat | Dog"


def companion_from_json(data: Any) -> Companion:
    """
    Build a :py:data:`Companion` member from one decoded JSON value.

    :param data: the decoded JSON value
    :return: the matching member
    :raises ValueError: if the value matches no member
    """
    if data.get("species") == "cat":
        return cat_from_json(data)
    if data.get("species") == "Dog":
        return dog_from_json(data)
    raise ValueError("the payload matches no member of Companion")


@dataclass
class Pet:
    """One pet of the store."""

    #: The pet's unique identifier.
    id: int
    name: str
    #: The pet's sale status.
    status: PetStatus | None = None
    #: The pet's day of birth.
    #: Unknown for pets rescued from the wild.
    born_on: datetime.date | None = None
    owner: Owner | None = None
    labels: dict[str, str] | None = None
    friends: list[Pet] | None = None
    #: A pet's companion animal.
    companion: Companion | None = None


def pet_from_json(data: Any) -> Pet:
    """
    Build a :py:class:`Pet` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the Pet
    """
    return Pet(
        id=data["id"],
        name=data["name"],
        status=PetStatus(data["status"]) if data.get("status") is not None else None,
        born_on=(
            datetime.date.fromisoformat(data["bornOn"]) if data.get("bornOn") is not None else None
        ),
        owner=owner_from_json(data["owner"]) if data.get("owner") is not None else None,
        labels=data.get("labels"),
        friends=(
            [pet_from_json(item) for item in data["friends"]]
            if data.get("friends") is not None
            else None
        ),
        companion=(
            companion_from_json(data["companion"]) if data.get("companion") is not None else None
        ),
    )


@dataclass
class Animal:
    """The ``Animal`` model."""

    species: str
    name: str


def animal_from_json(data: Any) -> Animal:
    """
    Build a :py:class:`Animal` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the Animal
    """
    return Animal(
        species=data["species"],
        name=data["name"],
    )


@dataclass
class CreateTokenResponse:
    """The ``CreateTokenResponse`` model."""

    #: The bearer token to present in the Authorization header.
    access_token: str
    expires_in: int | None = None


def create_token_response_from_json(data: Any) -> CreateTokenResponse:
    """
    Build a :py:class:`CreateTokenResponse` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the CreateTokenResponse
    """
    return CreateTokenResponse(
        access_token=data["access_token"],
        expires_in=data.get("expires_in"),
    )
