# generated by action0-client-openapi v0.1.0 from petstore.json — do not edit

from __future__ import annotations

import datetime
import enum
from dataclasses import dataclass
from typing import Any


class PetStatus(enum.Enum):
    """The pet's sale status."""

    AVAILABLE = "available"
    ON_SALE = "on-sale"
    SOLD = "sold"


@dataclass
class Owner:
    """The ``Owner`` model."""

    name: str
    class_: str | None = None


def owner_from_json(data: Any) -> Owner:
    """
    Build a :py:class:`Owner` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the Owner
    """
    return Owner(
        name=data["name"],
        class_=data.get("class"),
    )


@dataclass
class Pet:
    """One pet of the store."""

    id: int
    name: str
    status: PetStatus | None = None
    born_on: datetime.date | None = None
    owner: Owner | None = None
    labels: dict[str, str] | None = None
    friends: list[Pet] | None = None


def pet_from_json(data: Any) -> Pet:
    """
    Build a :py:class:`Pet` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the Pet
    """
    return Pet(
        id=data["id"],
        name=data["name"],
        status=PetStatus(data["status"]) if data.get("status") is not None else None,
        born_on=(
            datetime.date.fromisoformat(data["bornOn"]) if data.get("bornOn") is not None else None
        ),
        owner=owner_from_json(data["owner"]) if data.get("owner") is not None else None,
        labels=data.get("labels"),
        friends=(
            [pet_from_json(item) for item in data["friends"]]
            if data.get("friends") is not None
            else None
        ),
    )


@dataclass
class CreateTokenResponse:
    """The ``CreateTokenResponse`` model."""

    access_token: str
    expires_in: int | None = None


def create_token_response_from_json(data: Any) -> CreateTokenResponse:
    """
    Build a :py:class:`CreateTokenResponse` from one decoded JSON object.

    :param data: the decoded JSON object
    :return: the CreateTokenResponse
    """
    return CreateTokenResponse(
        access_token=data["access_token"],
        expires_in=data.get("expires_in"),
    )
