# generated by action0-client-openapi v0.1.0 from petstore.json — do not edit

from __future__ import annotations

import uuid
from typing import Any

from action0.client import JsonOperation
from action0.client import Operation
from action0.client import body
from action0.client import form_field
from action0.client import header
from action0.client import json_body
from action0.client import json_field
from action0.client import path_param
from action0.client import query
from action0.req import Method
from action0.req import Response

from .models import CreateTokenResponse
from .models import Pet
from .models import create_token_response_from_json
from .models import pet_from_json


class ListPets(JsonOperation[list[Pet]]):
    """``GET /pets`` — List all pets."""

    method = Method.GET
    path = "/pets"

    #: How many pets to return at most. The server caps this at 100; anything above is silently
    #: reduced to the first hundred matches.
    limit: int = query(default=20)
    tags: list[str] | None = query(default=None)
    x_request_id: uuid.UUID | None = header("X-Request-Id", default=None, serialize=str)

    def load_json(self, data: Any) -> list[Pet]:
        """
        :param data: the decoded JSON payload
        :return: the parsed result
        """
        return [pet_from_json(item) for item in data]


class CreatePet(JsonOperation[Pet]):
    """``POST /pets``"""

    method = Method.POST
    path = "/pets"

    #: The pet's display name.
    name: str = json_field()
    tag: str | None = json_field(default=None)

    def load_json(self, data: Any) -> Pet:
        """
        :param data: the decoded JSON payload
        :return: the parsed result
        """
        return pet_from_json(data)


class GetPet(JsonOperation[Pet]):
    """``GET /pets/{petId}``"""

    method = Method.GET
    path = "/pets/{pet_id}"
    # the schema spells the path "/pets/{petId}"

    #: The identifier of the pet to operate on.
    pet_id: int = path_param()

    def load_json(self, data: Any) -> Pet:
        """
        :param data: the decoded JSON payload
        :return: the parsed result
        """
        return pet_from_json(data)


class ReplacePet(JsonOperation[Pet]):
    """``PUT /pets/{petId}``"""

    method = Method.PUT
    path = "/pets/{pet_id}"
    # the schema spells the path "/pets/{petId}"

    #: The identifier of the pet to operate on.
    pet_id: int = path_param()
    #: One pet of the store.
    payload: Pet = json_body()

    def load_json(self, data: Any) -> Pet:
        """
        :param data: the decoded JSON payload
        :return: the parsed result
        """
        return pet_from_json(data)


class DeletePet(Operation[None]):
    """``DELETE /pets/{petId}``"""

    method = Method.DELETE
    path = "/pets/{pet_id}"
    # the schema spells the path "/pets/{petId}"

    #: The identifier of the pet to operate on.
    pet_id: int = path_param()

    def load(self, response: Response) -> None:
        """
        :param response: the checked response
        :return: the parsed result
        """
        return None


class UploadPetPhoto(Operation[None]):
    """``PUT /pets/{petId}/photo``"""

    method = Method.PUT
    path = "/pets/{pet_id}/photo"
    # the schema spells the path "/pets/{petId}/photo"

    pet_id: int = path_param()
    #: The request body's media type.
    content_type: str = header("Content-Type", default="image/png")
    payload: bytes = body()

    def load(self, response: Response) -> None:
        """
        :param response: the checked response
        :return: the parsed result
        """
        return None


class GetPetPhoto(Operation[bytes]):
    """``GET /pets/{petId}/photo``"""

    method = Method.GET
    path = "/pets/{pet_id}/photo"
    # the schema spells the path "/pets/{petId}/photo"

    pet_id: int = path_param()

    def load(self, response: Response) -> bytes:
        """
        :param response: the checked response
        :return: the parsed result
        """
        return response.body_bytes() or b""


class CreateToken(JsonOperation[CreateTokenResponse]):
    """``POST /oauth/token``"""

    method = Method.POST
    path = "/oauth/token"

    #: The OAuth grant type.
    grant_type: str = form_field()
    scope: str | None = form_field(default=None)

    def load_json(self, data: Any) -> CreateTokenResponse:
        """
        :param data: the decoded JSON payload
        :return: the parsed result
        """
        return create_token_response_from_json(data)
