import datetime
import re
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path
from typing import Any

from action0.openapi import Api
from action0.openapi import ArrayType
from action0.openapi import EnumModel
from action0.openapi import EnumType
from action0.openapi import Field
from action0.openapi import MapType
from action0.openapi import Model
from action0.openapi import OperationIR
from action0.openapi import Param
from action0.openapi import ParamLocation
from action0.openapi import ResponseKind
from action0.openapi import Scalar
from action0.openapi import ScalarType
from action0.openapi import load_schema
from action0.openapi import parse_api
from action0.openapi.generate import generate_package
from action0.openapi.generate import write_package
from action0.openapi.render import Imports
from action0.openapi.render import Lines
from action0.openapi.render import render_models
from action0.openapi.render import render_operations

FIXTURES = Path(__file__).parent / "fixtures"
GOLDEN = Path(__file__).parent / "golden" / "petstore_client"

#: the header line used by the golden files (the version is normalized
#: away in comparisons)
HEADER = "generated by action0-client-openapi v0.1.0 from petstore.json — do not edit"


def normalized(text: str) -> str:
    """
    Erase the generator version from a header for comparison.

    :param text: the module text
    :return: the text with the version replaced by ``vX``
    """
    return re.sub(r"action0-client-openapi v\S+", "action0-client-openapi vX", text)


def render_fixture() -> str:
    """
    Render the petstore fixture's models module.

    :return: the module text
    """
    return render_models(parse_api(load_schema(FIXTURES / "petstore.json")), HEADER)


class LinesTestCase(unittest.TestCase):
    """
    tests for :py:class:`action0.openapi.render.Lines`
    """

    def test_indentation(self) -> None:
        """
        Test indent/dedent and blank lines staying unindented.
        """
        lines = Lines()
        lines.write("class A:")
        lines.indent()
        lines.write("x = 1")
        lines.write()
        lines.write("y = 2")
        lines.dedent()
        self.assertEqual(lines.text(), "class A:\n    x = 1\n\n    y = 2\n")

    def test_separate(self) -> None:
        """
        Test that separate() normalizes to exactly n blank lines and
        does nothing at the start of a module.
        """
        lines = Lines()
        lines.separate()
        lines.write("a = 1")
        lines.write()
        lines.separate()
        lines.write("b = 2")
        self.assertEqual(lines.text(), "a = 1\n\n\nb = 2\n")

    def test_comments(self) -> None:
        """
        Test ``#:`` doc-comments: wrapping to the line limit at the
        current indentation, blank lines dropped, unbreakable tokens
        kept whole.
        """
        lines = Lines()
        lines.indent()
        lines.comment("Short.")
        lines.comment("First paragraph.\n\nSecond paragraph.")
        lines.comment("word " * 30)
        for line in lines.text().splitlines():
            self.assertLessEqual(len(line), 99)
        self.assertEqual(
            lines.text().splitlines()[:3],
            ["    #: Short.", "    #: First paragraph.", "    #: Second paragraph."],
        )
        unbreakable = Lines()
        unbreakable.comment("https://example.com/" + "x" * 120)
        (line,) = unbreakable.text().splitlines()
        self.assertEqual(line, "#: https://example.com/" + "x" * 120)

    def test_docstrings(self) -> None:
        """
        Test one-line and block docstrings, and quote defusing.
        """
        lines = Lines()
        lines.docstring("One pet.")
        lines.docstring("Line one.\n\nLine two.")
        lines.docstring('evil """ quotes')
        self.assertEqual(
            lines.text(),
            '"""One pet."""\n"""\nLine one.\n\nLine two.\n"""\n"""evil \'\'\' quotes"""\n',
        )


class ImportsTestCase(unittest.TestCase):
    """
    tests for :py:class:`action0.openapi.render.Imports`
    """

    def test_blocks_and_order(self) -> None:
        """
        Test the isort block order: __future__, stdlib (plain imports
        before from-imports), action0, relative — deduplicated.
        """
        imports = Imports()
        imports.add(
            "from typing import Any",
            "import uuid",
            "from .models import Pet",
            "from action0.client import JsonOperation",
            "from action0.req import Method",
            "import datetime",
            "from dataclasses import dataclass",
            "from __future__ import annotations",
            "import datetime",
        )
        lines = Lines()
        imports.render(lines)
        self.assertEqual(
            lines.text(),
            "from __future__ import annotations\n"
            "\n"
            "import datetime\n"
            "import uuid\n"
            "from dataclasses import dataclass\n"
            "from typing import Any\n"
            "\n"
            "from action0.client import JsonOperation\n"
            "from action0.req import Method\n"
            "\n"
            "from .models import Pet\n",
        )


class RenderModelsTestCase(unittest.TestCase):
    """
    tests for :py:func:`action0.openapi.render.render_models`
    """

    def test_empty_api(self) -> None:
        """
        Test that an API without models renders header and future
        import only.
        """
        text = render_models(Api(title="T", version="1"), "header line")
        self.assertEqual(text, "# header line\n\nfrom __future__ import annotations\n")

    def test_enum_only_module_needs_no_dataclass_import(self) -> None:
        """
        Test that imports are collected from what is actually rendered.
        """
        api = Api(
            title="T",
            version="1",
            models=(EnumModel(name="Status", base=Scalar.STR, members=(("OK", "ok"),)),),
        )
        text = render_models(api, "h")
        self.assertIn("import enum", text)
        self.assertNotIn("dataclass", text)
        self.assertNotIn("typing", text)

    def test_required_date_needs_no_none_guard(self) -> None:
        """
        Test the conversion of a required non-nullable rich scalar.
        """
        api = Api(
            title="T",
            version="1",
            models=(
                Model(
                    name="Event",
                    fields=(
                        Field(
                            name="at",
                            wire_name="at",
                            type=ScalarType(Scalar.DATETIME),
                            required=True,
                        ),
                    ),
                ),
            ),
        )
        self.assertIn('at=datetime.datetime.fromisoformat(data["at"]),', render_models(api, "h"))

    def test_field_description_becomes_comment(self) -> None:
        """
        Test that a field's schema description renders as a ``#:``
        doc-comment directly above the field.
        """
        api = Api(
            title="T",
            version="1",
            models=(
                Model(
                    name="Pet",
                    fields=(
                        Field(
                            name="id",
                            wire_name="id",
                            type=ScalarType(Scalar.INT),
                            required=True,
                            description="The pet's unique identifier.",
                        ),
                    ),
                ),
            ),
        )
        self.assertIn(
            "    #: The pet's unique identifier.\n    id: int\n", render_models(api, "h")
        )

    def test_matches_golden(self) -> None:
        """
        Test that the petstore fixture renders exactly the checked-in
        golden module (modulo the generator version).
        """
        expected = (GOLDEN / "models.py").read_text(encoding="utf-8")
        self.assertEqual(normalized(render_fixture()), normalized(expected))


class RenderOperationsTestCase(unittest.TestCase):
    """
    tests for :py:func:`action0.openapi.render.render_operations`
    """

    def operation_module(self, response_type: Any) -> str:
        """
        Render a module with one GET operation of the given JSON result.

        :param response_type: the response's IR type
        :return: the module text
        """
        api = Api(
            title="T",
            version="1",
            operations=(
                OperationIR(
                    class_name="GetThing",
                    method="GET",
                    path_template="/thing",
                    wire_path="/thing",
                    response_kind=ResponseKind.MODEL,
                    response_type=response_type,
                ),
            ),
        )
        return render_operations(api, "h")

    def test_unconverted_json_result_is_cast(self) -> None:
        """
        Test that a JSON result needing no conversion is returned
        through typing.cast — plain ``return data`` would fail mypy
        strict's no-any-return.
        """
        text = self.operation_module(MapType(ScalarType(Scalar.INT)))
        self.assertIn("from typing import cast", text)
        self.assertIn("        return cast(dict[str, int], data)\n", text)

    def test_any_json_result_needs_no_cast(self) -> None:
        """
        Test that an ``Any`` result stays a plain return — there is
        nothing to cast to.
        """
        text = self.operation_module(ScalarType(Scalar.ANY))
        self.assertIn("        return data\n", text)
        self.assertNotIn("cast", text)


class JoinedParameterRenderTestCase(unittest.TestCase):
    """
    tests for the ``serialize=`` join expressions of non-exploded array
    parameters
    """

    def module_text(self, item: Any, join_with: str = ",") -> str:
        """
        Render one operation with one joined array parameter.

        :param item: the array's item type
        :param join_with: the separator
        :return: the rendered operations module (an over-long field
            wraps, so assertions search the whole text)
        """
        api = Api(
            title="T",
            version="1",
            models=(EnumModel(name="Color", base=Scalar.STR, members=(("RED", "red"),)),),
            operations=(
                OperationIR(
                    class_name="ListThings",
                    method="GET",
                    path_template="/things",
                    wire_path="/things",
                    params=(
                        Param(
                            name="values",
                            wire_name="values",
                            location=ParamLocation.QUERY,
                            type=ArrayType(item),
                            required=False,
                            join_with=join_with,
                        ),
                    ),
                ),
            ),
        )
        return render_operations(api, "h")

    def test_join_expressions(self) -> None:
        """
        Test the item expression per joinable type, and the separator.
        """
        join = "serialize=lambda values:"
        cases = [
            (ScalarType(Scalar.STR), ",", f'{join} ",".join(values)'),
            (ScalarType(Scalar.STR), "|", f'{join} "|".join(values)'),
            (
                ScalarType(Scalar.INT),
                ",",
                f'{join} ",".join(str(item) for item in values)',
            ),
            (
                ScalarType(Scalar.BOOL),
                ",",
                f'{join} ",".join("true" if item else "false" for item in values)',
            ),
            (
                ScalarType(Scalar.DATE),
                ",",
                f'{join} ",".join(item.isoformat() for item in values)',
            ),
            (
                ScalarType(Scalar.UUID),
                ",",
                f'{join} ",".join(str(item) for item in values)',
            ),
            (
                EnumType("Color"),
                " ",
                f'{join} " ".join(str(item.value) for item in values)',
            ),
        ]
        for item, separator, expected in cases:
            with self.subTest(item=item, separator=separator):
                self.assertIn(expected, self.module_text(item, separator))


class GoldenBehaviorTestCase(unittest.TestCase):
    """
    tests that the rendered converter functions actually work
    """

    namespace: dict[str, Any]

    @classmethod
    def setUpClass(cls) -> None:
        cls.namespace = {}
        exec(compile(render_fixture(), "models.py", "exec"), cls.namespace)

    def test_full_payload(self) -> None:
        """
        Test converting a payload using every conversion shape: enum,
        nullable date, nested model, map, and a list of self references.
        """
        pet_from_json = self.namespace["pet_from_json"]
        pet = pet_from_json(
            {
                "id": 1,
                "name": "Rex",
                "status": "on-sale",
                "bornOn": "2020-05-04",
                "owner": {"name": "Simon", "class": "human"},
                "labels": {"chip": "yes"},
                "friends": [{"id": 2, "name": "Lassie"}],
                "companion": {"species": "cat", "name": "Tom", "meow": True},
            }
        )
        self.assertEqual(pet.status, self.namespace["PetStatus"].ON_SALE)
        self.assertEqual(pet.born_on, datetime.date(2020, 5, 4))
        self.assertEqual(pet.owner.class_, "human")
        self.assertEqual(pet.labels, {"chip": "yes"})
        self.assertEqual(pet.friends[0].name, "Lassie")
        self.assertIsNone(pet.friends[0].status)
        self.assertIsInstance(pet.companion, self.namespace["Cat"])
        self.assertTrue(pet.companion.meow)

    def test_union_dispatch(self) -> None:
        """
        Test the discriminated union converter: explicit and implicit
        tags, and the unknown-tag error.
        """
        companion_from_json = self.namespace["companion_from_json"]
        dog = companion_from_json({"species": "Dog", "name": "Rex", "bark": False})
        self.assertIsInstance(dog, self.namespace["Dog"])
        cat = companion_from_json({"species": "cat", "name": "Tom", "meow": True})
        self.assertIsInstance(cat, self.namespace["Cat"])
        with self.assertRaisesRegex(ValueError, "no member of Companion"):
            companion_from_json({"species": "fish", "name": "Nemo"})

    def test_missing_optionals_and_nulls(self) -> None:
        """
        Test that omitted and null optionals both come out as None.
        """
        pet = self.namespace["pet_from_json"]({"id": 1, "name": "Rex", "bornOn": None})
        self.assertIsNone(pet.status)
        self.assertIsNone(pet.born_on)
        self.assertIsNone(pet.friends)

    def test_missing_required_raises(self) -> None:
        """
        Test that a payload missing a required key raises KeyError.
        """
        with self.assertRaises(KeyError):
            self.namespace["pet_from_json"]({"name": "Rex"})

    def test_catch_all_collects_undeclared_keys(self) -> None:
        """
        Test that payload keys outside the declared properties land in
        the catch-all field — and declared ones do not.
        """
        record = self.namespace["health_record_from_json"](
            {"clinic": "Vet Praxis", "examinedOn": None, "weight": 7.4, "temperature": 38.6}
        )
        self.assertEqual(record.additional_properties, {"weight": 7.4, "temperature": 38.6})
        self.assertEqual(record.clinic, "Vet Praxis")
        empty = self.namespace["health_record_from_json"]({"clinic": "Vet", "examinedOn": None})
        self.assertEqual(empty.additional_properties, {})


class GoldenToolchainTestCase(unittest.TestCase):
    """
    tests that the golden package satisfies ruff (the type checkers
    cover it via the repository-wide runs, since it lives in tests/)
    """

    def ruff(self, *arguments: str) -> None:
        """
        Run ruff over the golden package and assert it is happy.

        :param arguments: the ruff subcommand and its arguments
        """
        ruff = shutil.which("ruff")
        assert ruff is not None, "ruff must be installed (it is a dev dependency)"
        result = subprocess.run(
            [ruff, *arguments, str(GOLDEN)],
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_format(self) -> None:
        """
        Test that ruff format would not change the golden package.
        """
        self.ruff("format", "--check")

    def test_lint(self) -> None:
        """
        Test that ruff check (incl. import sorting) passes.
        """
        self.ruff("check")


class WrappingTestCase(unittest.TestCase):
    """
    tests that over-long constructs are laid out exactly as ruff format
    lays them out (the longnames fixture's names are sized to overflow
    the 99-column limit in every supported spot)
    """

    files: dict[str, str]

    @classmethod
    def setUpClass(cls) -> None:
        api = parse_api(load_schema(FIXTURES / "longnames.json"))
        cls.files = generate_package(
            api, client_name="LongnamesClient", schema_name="longnames.json"
        )

    def test_converter_def_wraps(self) -> None:
        """
        Test that an over-long converter signature explodes its one
        parameter with a trailing comma.
        """
        self.assertIn(
            "def modelwithanextremelylonggeneratedpythonclassnameforwrapping_from_json(\n"
            "    data: Any,\n"
            ") -> Modelwithanextremelylonggeneratedpythonclassnameforwrapping:\n",
            self.files["models.py"],
        )

    def test_comprehension_splits(self) -> None:
        """
        Test that an over-long list comprehension opens its bracket.
        """
        self.assertIn(
            "        items=(\n"
            "            [\n"
            "                modelwithanextremelylonggeneratedpythonclassnameforwrapping_from_json"
            "(item)\n"
            '                for item in data["items"]\n'
            "            ]\n"
            "        ),\n",
            self.files["models.py"],
        )

    def test_guarded_comprehension_splits(self) -> None:
        """
        Test that the comprehension also splits inside an if/else guard.
        """
        self.assertIn(
            "        maybe=(\n"
            "            [\n"
            "                modelwithanextremelylonggeneratedpythonclassnameforwrapping_from_json"
            "(item)\n"
            '                for item in data["maybe"]\n'
            "            ]\n"
            '            if data.get("maybe") is not None\n'
            "            else None\n"
            "        ),\n",
            self.files["models.py"],
        )

    def test_nested_comprehension_splits_recursively(self) -> None:
        """
        Test that a nested comprehension splits its inner level too.
        """
        self.assertIn(
            "        matrix=(\n"
            "            [\n"
            "                [\n"
            "                    modelwithanextremelylonggeneratedpythonclassnameforwrapping"
            "_from_json(item1)\n"
            "                    for item1 in item\n"
            "                ]\n"
            '                for item in data["matrix"]\n'
            "            ]\n"
            "        ),\n",
            self.files["models.py"],
        )

    def test_dict_comprehension_splits(self) -> None:
        """
        Test that an over-long dict comprehension opens its brace.
        """
        self.assertIn(
            "        labels=(\n"
            "            {\n"
            "                key: modelwithanextremelylonggeneratedpythonclassnameforwrapping"
            "_from_json(value)\n"
            '                for key, value in data["labels"].items()\n'
            "            }\n"
            "        ),\n",
            self.files["models.py"],
        )

    def test_properties_constant_wraps(self) -> None:
        """
        Test that an over-long declared-properties constant opens its
        set with one element per line and a magic trailing comma.
        """
        self.assertIn(
            "_CATCHALLMODELWITHANEXTREMELYLONGGENERATEDPYTHONCLASSNAME_PROPERTIES = {\n"
            '    "declaredpropertyfirst",\n'
            '    "declaredpropertysecondwithalongname",\n'
            '    "declaredpropertythirdwithanevenlongername",\n'
            "}\n",
            self.files["models.py"],
        )

    def test_catch_all_comprehension_splits_with_filter(self) -> None:
        """
        Test that the catch-all comprehension puts its for clause and
        its if filter on lines of their own.
        """
        self.assertIn(
            "        additional_properties=(\n"
            "            {\n"
            "                key: modelwithanextremelylonggeneratedpythonclassnameforwrapping"
            "_from_json(value)\n"
            "                for key, value in data.items()\n"
            "                if key not in "
            "_CATCHALLMODELWITHANEXTREMELYLONGGENERATEDPYTHONCLASSNAME_PROPERTIES\n"
            "            }\n"
            "        ),\n",
            self.files["models.py"],
        )

    def test_catch_all_filter_splits_before_not_in(self) -> None:
        """
        Test that an over-long if filter breaks before ``not in``, the
        way ruff format breaks it.
        """
        self.assertIn(
            "                key: value\n"
            "                for key, value in data.items()\n"
            "                if key\n"
            "                not in "
            "_CATCHALLMODELWITHANABSURDLYLONGGENERATEDPYTHONCLASSNAMEINDEED_PROPERTIES\n",
            self.files["models.py"],
        )

    def test_model_field_wraps(self) -> None:
        """
        Test the two model-field layouts: value parenthesized when the
        head fits, annotation parenthesized when it does not.
        """
        self.assertIn(
            "    optionalitemsone: "
            "list[Modelwithanextremelylonggeneratedpythonclassnameforwrapping] | None = (\n"
            "        None\n"
            "    )\n",
            self.files["models.py"],
        )
        self.assertIn(
            "    optionalfieldwithalongername: (\n"
            "        list[Modelwithanextremelylonggeneratedpythonclassnameforwrapping] | None\n"
            "    ) = None\n",
            self.files["models.py"],
        )

    def test_operation_class_header_wraps(self) -> None:
        """
        Test that an over-long operation base moves to its own line.
        """
        self.assertIn(
            "class ListLongThings(\n"
            "    JsonOperation[list[Modelwithanextremelylonggeneratedpythonclassnameforwrapping]]"
            "\n):\n",
            self.files["operations.py"],
        )

    def test_operation_field_wraps(self) -> None:
        """
        Test the three field layouts ruff format uses in turn: argument
        one line deeper, whole call parenthesized, annotation
        parenthesized.
        """
        operations = self.files["operations.py"]
        self.assertIn(
            "    secondparamname: Enumerationwithanextremelylonggeneratedpythonclassname"
            " = query(\n"
            "        default=Enumerationwithanextremelylonggeneratedpythonclassname.FIRST\n"
            "    )\n",
            operations,
        )
        self.assertIn(
            "    thirdparameterlonger:"
            " list[Enumerationwithanextremelylonggeneratedpythonclassname] | None = (\n"
            "        query(default=None)\n"
            "    )\n",
            operations,
        )
        self.assertIn(
            "    fourthparameterwithamuchlongername: (\n"
            "        Enumerationwithanextremelylonggeneratedpythonclassname | None\n"
            "    ) = query(default=None)\n",
            operations,
        )

    def test_load_json_def_and_return_wrap(self) -> None:
        """
        Test that an over-long ``load_json`` puts its parameters on one
        shared line and splits the returned comprehension.
        """
        operations = self.files["operations.py"]
        self.assertIn(
            "    def load_json(\n"
            "        self, data: Any\n"
            "    ) -> list[Modelwithanextremelylonggeneratedpythonclassnameforwrapping]:\n",
            operations,
        )
        self.assertIn(
            "        return [\n"
            "            modelwithanextremelylonggeneratedpythonclassnameforwrapping"
            "_from_json(item)\n"
            "            for item in data\n"
            "        ]\n",
            operations,
        )

    def test_fieldless_operation_single_blank_line(self) -> None:
        """
        Test that an operation without fields keeps a single blank line
        between its path and its load method.
        """
        self.assertIn(
            '    path = "/plain"\n\n    def load(self, response: Response) -> bytes:\n',
            self.files["operations.py"],
        )

    def test_over_long_alias_stays(self) -> None:
        """
        Test that an alias parentheses would not save stays on one line
        (ruff format leaves it alone too).
        """
        self.assertIn(
            'Longunion: TypeAlias = "Firstunionmemberwithanextremelylonggeneratedclassname |'
            ' Secondunionmemberwithanextremelylonggeneratedclassname"\n',
            self.files["models.py"],
        )

    def test_package_is_ruff_clean(self) -> None:
        """
        Test that the whole generated package satisfies ruff format and
        ruff check under the repository configuration.
        """
        ruff = shutil.which("ruff")
        assert ruff is not None, "ruff must be installed (it is a dev dependency)"
        config = Path(__file__).parents[3] / "pyproject.toml"
        with tempfile.TemporaryDirectory() as tmp:
            package = Path(tmp) / "longnames_client"
            write_package(self.files, package)
            for arguments in (["format", "--check"], ["check"]):
                result = subprocess.run(
                    [ruff, *arguments, "--config", str(config), str(package)],
                    capture_output=True,
                    text=True,
                    check=False,
                )
                self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
