import datetime
import re
import shutil
import subprocess
import unittest
from pathlib import Path
from typing import Any

from action0.openapi import Api
from action0.openapi import EnumModel
from action0.openapi import Field
from action0.openapi import Model
from action0.openapi import Scalar
from action0.openapi import ScalarType
from action0.openapi import load_schema
from action0.openapi import parse_api
from action0.openapi.render import Imports
from action0.openapi.render import Lines
from action0.openapi.render import render_models

FIXTURES = Path(__file__).parent / "fixtures"
GOLDEN = Path(__file__).parent / "golden" / "petstore_client"

#: the header line used by the golden files (the version is normalized
#: away in comparisons)
HEADER = "generated by action0-client-openapi v0.1.0 from petstore.json — do not edit"


def normalized(text: str) -> str:
    """
    Erase the generator version from a header for comparison.

    :param text: the module text
    :return: the text with the version replaced by ``vX``
    """
    return re.sub(r"action0-client-openapi v\S+", "action0-client-openapi vX", text)


def render_fixture() -> str:
    """
    Render the petstore fixture's models module.

    :return: the module text
    """
    return render_models(parse_api(load_schema(FIXTURES / "petstore.json")), HEADER)


class LinesTestCase(unittest.TestCase):
    """
    tests for :py:class:`action0.openapi.render.Lines`
    """

    def test_indentation(self) -> None:
        """
        Test indent/dedent and blank lines staying unindented.
        """
        lines = Lines()
        lines.write("class A:")
        lines.indent()
        lines.write("x = 1")
        lines.write()
        lines.write("y = 2")
        lines.dedent()
        self.assertEqual(lines.text(), "class A:\n    x = 1\n\n    y = 2\n")

    def test_separate(self) -> None:
        """
        Test that separate() normalizes to exactly n blank lines and
        does nothing at the start of a module.
        """
        lines = Lines()
        lines.separate()
        lines.write("a = 1")
        lines.write()
        lines.separate()
        lines.write("b = 2")
        self.assertEqual(lines.text(), "a = 1\n\n\nb = 2\n")

    def test_comments(self) -> None:
        """
        Test ``#:`` doc-comments: wrapping to the line limit at the
        current indentation, blank lines dropped, unbreakable tokens
        kept whole.
        """
        lines = Lines()
        lines.indent()
        lines.comment("Short.")
        lines.comment("First paragraph.\n\nSecond paragraph.")
        lines.comment("word " * 30)
        for line in lines.text().splitlines():
            self.assertLessEqual(len(line), 99)
        self.assertEqual(
            lines.text().splitlines()[:3],
            ["    #: Short.", "    #: First paragraph.", "    #: Second paragraph."],
        )
        unbreakable = Lines()
        unbreakable.comment("https://example.com/" + "x" * 120)
        (line,) = unbreakable.text().splitlines()
        self.assertEqual(line, "#: https://example.com/" + "x" * 120)

    def test_docstrings(self) -> None:
        """
        Test one-line and block docstrings, and quote defusing.
        """
        lines = Lines()
        lines.docstring("One pet.")
        lines.docstring("Line one.\n\nLine two.")
        lines.docstring('evil """ quotes')
        self.assertEqual(
            lines.text(),
            '"""One pet."""\n"""\nLine one.\n\nLine two.\n"""\n"""evil \'\'\' quotes"""\n',
        )


class ImportsTestCase(unittest.TestCase):
    """
    tests for :py:class:`action0.openapi.render.Imports`
    """

    def test_blocks_and_order(self) -> None:
        """
        Test the isort block order: __future__, stdlib (plain imports
        before from-imports), action0, relative — deduplicated.
        """
        imports = Imports()
        imports.add(
            "from typing import Any",
            "import uuid",
            "from .models import Pet",
            "from action0.client import JsonOperation",
            "from action0.req import Method",
            "import datetime",
            "from dataclasses import dataclass",
            "from __future__ import annotations",
            "import datetime",
        )
        lines = Lines()
        imports.render(lines)
        self.assertEqual(
            lines.text(),
            "from __future__ import annotations\n"
            "\n"
            "import datetime\n"
            "import uuid\n"
            "from dataclasses import dataclass\n"
            "from typing import Any\n"
            "\n"
            "from action0.client import JsonOperation\n"
            "from action0.req import Method\n"
            "\n"
            "from .models import Pet\n",
        )


class RenderModelsTestCase(unittest.TestCase):
    """
    tests for :py:func:`action0.openapi.render.render_models`
    """

    def test_empty_api(self) -> None:
        """
        Test that an API without models renders header and future
        import only.
        """
        text = render_models(Api(title="T", version="1"), "header line")
        self.assertEqual(text, "# header line\n\nfrom __future__ import annotations\n")

    def test_enum_only_module_needs_no_dataclass_import(self) -> None:
        """
        Test that imports are collected from what is actually rendered.
        """
        api = Api(
            title="T",
            version="1",
            models=(EnumModel(name="Status", base=Scalar.STR, members=(("OK", "ok"),)),),
        )
        text = render_models(api, "h")
        self.assertIn("import enum", text)
        self.assertNotIn("dataclass", text)
        self.assertNotIn("typing", text)

    def test_required_date_needs_no_none_guard(self) -> None:
        """
        Test the conversion of a required non-nullable rich scalar.
        """
        api = Api(
            title="T",
            version="1",
            models=(
                Model(
                    name="Event",
                    fields=(
                        Field(
                            name="at",
                            wire_name="at",
                            type=ScalarType(Scalar.DATETIME),
                            required=True,
                        ),
                    ),
                ),
            ),
        )
        self.assertIn('at=datetime.datetime.fromisoformat(data["at"]),', render_models(api, "h"))

    def test_field_description_becomes_comment(self) -> None:
        """
        Test that a field's schema description renders as a ``#:``
        doc-comment directly above the field.
        """
        api = Api(
            title="T",
            version="1",
            models=(
                Model(
                    name="Pet",
                    fields=(
                        Field(
                            name="id",
                            wire_name="id",
                            type=ScalarType(Scalar.INT),
                            required=True,
                            description="The pet's unique identifier.",
                        ),
                    ),
                ),
            ),
        )
        self.assertIn(
            "    #: The pet's unique identifier.\n    id: int\n", render_models(api, "h")
        )

    def test_matches_golden(self) -> None:
        """
        Test that the petstore fixture renders exactly the checked-in
        golden module (modulo the generator version).
        """
        expected = (GOLDEN / "models.py").read_text(encoding="utf-8")
        self.assertEqual(normalized(render_fixture()), normalized(expected))


class GoldenBehaviorTestCase(unittest.TestCase):
    """
    tests that the rendered converter functions actually work
    """

    namespace: dict[str, Any]

    @classmethod
    def setUpClass(cls) -> None:
        cls.namespace = {}
        exec(compile(render_fixture(), "models.py", "exec"), cls.namespace)

    def test_full_payload(self) -> None:
        """
        Test converting a payload using every conversion shape: enum,
        nullable date, nested model, map, and a list of self references.
        """
        pet_from_json = self.namespace["pet_from_json"]
        pet = pet_from_json(
            {
                "id": 1,
                "name": "Rex",
                "status": "on-sale",
                "bornOn": "2020-05-04",
                "owner": {"name": "Simon", "class": "human"},
                "labels": {"chip": "yes"},
                "friends": [{"id": 2, "name": "Lassie"}],
                "companion": {"species": "cat", "name": "Tom", "meow": True},
            }
        )
        self.assertEqual(pet.status, self.namespace["PetStatus"].ON_SALE)
        self.assertEqual(pet.born_on, datetime.date(2020, 5, 4))
        self.assertEqual(pet.owner.class_, "human")
        self.assertEqual(pet.labels, {"chip": "yes"})
        self.assertEqual(pet.friends[0].name, "Lassie")
        self.assertIsNone(pet.friends[0].status)
        self.assertIsInstance(pet.companion, self.namespace["Cat"])
        self.assertTrue(pet.companion.meow)

    def test_union_dispatch(self) -> None:
        """
        Test the discriminated union converter: explicit and implicit
        tags, and the unknown-tag error.
        """
        companion_from_json = self.namespace["companion_from_json"]
        dog = companion_from_json({"species": "Dog", "name": "Rex", "bark": False})
        self.assertIsInstance(dog, self.namespace["Dog"])
        cat = companion_from_json({"species": "cat", "name": "Tom", "meow": True})
        self.assertIsInstance(cat, self.namespace["Cat"])
        with self.assertRaisesRegex(ValueError, "no member of Companion"):
            companion_from_json({"species": "fish", "name": "Nemo"})

    def test_missing_optionals_and_nulls(self) -> None:
        """
        Test that omitted and null optionals both come out as None.
        """
        pet = self.namespace["pet_from_json"]({"id": 1, "name": "Rex", "bornOn": None})
        self.assertIsNone(pet.status)
        self.assertIsNone(pet.born_on)
        self.assertIsNone(pet.friends)

    def test_missing_required_raises(self) -> None:
        """
        Test that a payload missing a required key raises KeyError.
        """
        with self.assertRaises(KeyError):
            self.namespace["pet_from_json"]({"name": "Rex"})


class GoldenToolchainTestCase(unittest.TestCase):
    """
    tests that the golden package satisfies ruff (the type checkers
    cover it via the repository-wide runs, since it lives in tests/)
    """

    def ruff(self, *arguments: str) -> None:
        """
        Run ruff over the golden package and assert it is happy.

        :param arguments: the ruff subcommand and its arguments
        """
        ruff = shutil.which("ruff")
        assert ruff is not None, "ruff must be installed (it is a dev dependency)"
        result = subprocess.run(
            [ruff, *arguments, str(GOLDEN)],
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_format(self) -> None:
        """
        Test that ruff format would not change the golden package.
        """
        self.ruff("format", "--check")

    def test_lint(self) -> None:
        """
        Test that ruff check (incl. import sorting) passes.
        """
        self.ruff("check")
